### ISSUE TITLE
Crash caused by extension

### ISSUE THREAD

**Issue by toddbranch** [AdrianHsu/cadenza-chrome-extension#1]
HI!  I run a website and we had a user experiencing crashes.  The crash seems to be related to this extension:
TypeError: Cannot read property 'query' of undefined
at sendMessageToActiveTab (chrome-extension://fcneeeckalcgcklbloocjmhapagkkbfa/controls.js:2:15)
at init (chrome-extension://fcneeeckalcgcklbloocjmhapagkkbfa/controls.js:48:3)
at chrome-extension://fcneeeckalcgcklbloocjmhapagkkbfa/controls.js:135:5
...code outside of the extension

Just an FYI.

**Comment by MikeFoden** [comment]
I've also seen the same issue from one of my workplaces' users.

**Comment by quisido** [comment]
This is seemingly still an issue. I logged this error 5 days ago:

```
TypeError
Cannot read property 'query' of undefined
```

Caused by `chrome-extension://fcneeeckalcgcklbloocjmhapagkkbfa/controls.js` in `sendMessageToActiveTab` at line 2 character 15.

**Comment by 3stacks** [comment]
I've also just had this crash occur on my website.
